name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리의 코드를 체크아웃합니다.
      - name: Check out the repository
        uses: actions/checkout@v3

      # Node.js 환경을 설정합니다.
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 프로젝트의 의존성을 설치합니다.
      - name: Install dependencies
        run: npm install

      # GitHub Secrets에서 SSH 키를 파일로 저장하고, 올바른 권한을 설정합니다.
      - name: Add SSH key
        run: |
          echo "$DEPLOY_KEY" > /tmp/deploy_key.pem
          chmod 600 /tmp/deploy_key.pem
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      # AWS EC2 인스턴스에 접속하여 애플리케이션을 배포합니다.
      - name: Deploy to AWS EC2
        run: |
          ssh -i /tmp/deploy_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-3-38-96-3.ap-northeast-2.compute.amazonaws.com << 'EOF'
          cd Pironeer_Attend_Web/
          pm2 stop app.js || true
          git pull origin main
          npm install --production
          pm2 start app.js
          EOF

      # 배포 후, SSH 키 파일을 명시적으로 삭제합니다.
      - name: Clean up
        run: rm /tmp/deploy_key.pem
